AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samlola003exam

  Sample SAM Template for samlola003exam
#Changegd the hello world template to be Image Gen
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  ImageGenFunctionRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "bedrock:InvokeModel"
                Resource:
                  - "arn:aws:s3:::pgr301-couch-explorers/*"  # Bucket name
                  - "arn:aws:bedrock:us-east-1::model/amazon.titan-image-generator-v1"  #Bedrockarn Potential error 

  ImageGenFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: image_Generator/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64
      Role: !GetAtt ImageGenFunctionRole.Arn #IAM role
      Events:
        ImageGenGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /imageGen
            Method: get
        ImageGenPost: #added post method
          Type: Api
          Properties:
            Path: /imageGen
            Method: post
      Environment:
        Variables:
          CouchExplorerBucket: "pgr301-couch-explorers"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ImageGenApi:
    Description: API Gateway endpoint URL for Prod stage for Image Generation function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/imageGen/"
  ImageGenFunction:
    Description: Image Generator Lambda Function ARN
    Value: !GetAtt ImageGenFunction.Arn
  ImageGenFunctionIamRole:
    Description: Implicit IAM Role created for Image Generatorfunction
    Value: !GetAtt ImageGenFunctionRole.Arn
