on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./java_sqs_client

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # Step 1: Checkout code + git version 
      - uses: actions/checkout@v3
      - name: Get next version number
        id: version
        run: |
          VERSION=$(git rev-list --count HEAD)  # Use commit count as version
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 2: Login to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: louisehjuler/23imagegen

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./java_sqs_client
          file: ./java_sqs_client/Dockerfile
          push: true
          tags: |
            louisehjuler/23imagegen:${{env.VERSION}}
            louisehjuler/23imagegen:latest